### ISSUE TITLE
Wrong key used after opening new fd?

### ISSUE THREAD

**Issue by ahwayakchih** [rvagg/node-fd#1]
Hi,

I may be wrong here, because i was just reading the code, not tried it yet, but shouldn't https://github.com/rvagg/node-fd/blob/ee2f8851540c69deb63079e46c77f159e64c3f74/index.js#L51

be this instead:

```js
this._fds[key(path, fd)] = 0
```
I think it does not break anything at the moment, because https://github.com/rvagg/node-fd/blob/ee2f8851540c69deb63079e46c77f159e64c3f74/index.js#L62 falls back to `0` anyway, but it probably does leak object keys, because the only place they are cleaned up is at https://github.com/rvagg/node-fd/blob/ee2f8851540c69deb63079e46c77f159e64c3f74/index.js#L17 and that one does use `key` method (which in turn generates string that differs from `fd + path`).

**Comment by rvagg** [comment]
yeah, I think you're right @ahwayakchih. It's been too long since I had my head in this code but going over it now I don't see any other references to `this._fds[fd + path]`, they are all this._fds[key(path, fd)] so it looks like a bug. Would you mind filling a pull request to rectify this and then I can do a bit more testing on it and get a fix out.

**Comment by rvagg** [comment]
thanks for spending the time to investigate this btw @ahwayakchih

**Comment by ahwayakchih** [comment]
@rvagg sure, no problem: #2
